debug: true

server:
  port: 8001
  context-path: /csdn
  
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/any?autoReconnect=true&amp;zeroDateTimeBehavior=convertToNull&amp;useUnicode=true&amp;characterEncoding=UTF-8
    username: root
    password: root
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
security:
  oauth2:
    client:
      client-id: csdn-app-client
      client-secret: csdn-app-secret
    resource:
      tokenInfoUri: http://127.0.0.1:8000/oauth/check_token
      userInfoUri: http://127.0.0.1:8000/me
      